# Generated by Django 2.2 on 2020-08-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0003_auto_20200728_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
