# Generated by Django 2.2 on 2020-08-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0004_post_my_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='my_image',
        ),
    ]
