# Generated by Django 2.2 on 2020-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0006_post_my_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
